ALTER TABLE pet ADD COLUMN chapeu VARCHAR(30) NOT NULL DEFAULT 'nenhum';
ALTER TABLE pet ADD COLUMN rosto VARCHAR(30) NOT NULL DEFAULT 'nenhum';
ALTER TABLE pet ADD COLUMN acessorio_corpo VARCHAR(30) NOT NULL DEFAULT 'nenhum';
