ALTER TABLE usuario ADD COLUMN tema VARCHAR(20) NOT NULL DEFAULT 'escuro';
ALTER TABLE usuario ADD COLUMN perfil_visualizacoes BIGINT NOT NULL DEFAULT 0;
ALTER TABLE link_usuario ADD COLUMN cliques BIGINT NOT NULL DEFAULT 0;
